format = """
$shlvl\
$directory\
$git_branch\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$buf\
$meson\
$spack\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$container\
$shell\
$character"""

[git_branch]
#style = "bold green"
truncation_length = 40
truncation_symbol = '...'
format = '[\($branch\)]($style)'

[directory]
truncation_length = 255
# truncation_symbol = 'â€¦/'
truncate_to_repo = false
use_logical_path = false
