general.import = [
  "catppuccin-mocha.toml"
]


[env]
TERM = "xterm-256color"


[window]
startup_mode = "Maximized"


[font]
size = 12.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold   = { family = "JetBrainsMono Nerd Font Mono", style = "Bold"   }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }


[terminal]
[terminal.shell]
program = "wsl"
args = ["--cd", "~"]
